/**
 * Hero Slider Configuration File.
 * Loads local video assets from /videos/ folder with fallback posters, luxury editorial labels,
 * headings, descriptions, and CTA configurations.
 */
export const HERO_SLIDES = [
  {
    id: 'wedding',
    label: 'Bespoke Weddings',
    heading: 'Crafting Unforgettable',
    highlightText: 'Wedding Moments',
    description: 'From grand royal receptions to intimate romantic vows, we design and produce world-class weddings tailored to your dream vision.',
    videoUrl: '/videos/wedding.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'Explore Packages',
    secondaryCtaLink: '/packages',
  },
  {
    id: 'corporate',
    label: 'Executive Galas & Summits',
    heading: 'Creating Extraordinary',
    highlightText: 'Corporate Experiences',
    description: 'High-impact annual galas, global leadership summits, and red-carpet product launches engineered with precision.',
    videoUrl: '/videos/corporate.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'View Services',
    secondaryCtaLink: '/services',
  },
  {
    id: 'birthday',
    label: 'Milestone Celebrations',
    heading: 'Celebrate Every Birthday',
    highlightText: 'In Unrivaled Style',
    description: 'Exclusive milestone bashes, private celebrity dinners, and immersive themed celebrations crafted for royalty.',
    videoUrl: '/videos/birthday.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'Browse Themes',
    secondaryCtaLink: '/themes',
  },
  {
    id: 'stage',
    label: 'Stage & Production',
    heading: 'Where Every Performance',
    highlightText: 'Becomes Legendary',
    description: 'Intelligent stage lighting, state-of-the-art acoustic engineering, and immersive visual production.',
    videoUrl: '/videos/stage.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'Explore Offerings',
    secondaryCtaLink: '/services',
  },
  {
    id: 'engagement',
    label: 'Eternal Vows & Soirées',
    heading: 'Cherished Beginnings &',
    highlightText: 'Eternal Vows',
    description: 'Enchanting floral installations, candlelit garden soirées, and timeless engagement celebrations.',
    videoUrl: '/videos/engagement.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'View Gallery',
    secondaryCtaLink: '/gallery',
  },
  {
    id: 'reception',
    label: 'Grand Evening Soirées',
    heading: 'Opulent Receptions &',
    highlightText: 'Luxury Hospitality',
    description: 'White-glove dining, champagne towers, and crystal chandeliers for night celebrations.',
    videoUrl: '/videos/reception.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1920&q=80',
    primaryCtaText: 'Inquire Event',
    primaryCtaLink: '/contact',
    secondaryCtaText: 'Explore Packages',
    secondaryCtaLink: '/packages',
  },
];
